// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var RepoItem$ReactTemplate = require("./RepoItem.bs.js");

var dummyRepo = /* record */[
  /* full_name */"jsdf/reason-react-hacker-news",
  /* stargazers_count */27,
  /* html_url */"https://github.com/jsdf/reason-react-hacker-news"
];

var optionalDummyRepo = dummyRepo;

function App(Props) {
  var match = React.useState((function () {
          return undefined;
        }));
  var setRepoData = match[1];
  var repoData = match[0];
  var loadedReposButton = React.createElement("button", {
        onClick: (function (_event) {
            return Curry._1(setRepoData, (function (_prev) {
                          return dummyRepo;
                        }));
          })
      }, "Load Repos");
  var repoItem = repoData !== undefined ? React.createElement(RepoItem$ReactTemplate.make, {
          repo: repoData
        }) : loadedReposButton;
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Reason Projects"), repoItem);
}

var make = App;

exports.dummyRepo = dummyRepo;
exports.optionalDummyRepo = optionalDummyRepo;
exports.make = make;
/* react Not a pure module */
