// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var RepoData$ReactTemplate = require("./RepoData.bs.js");
var RepoItem$ReactTemplate = require("./RepoItem.bs.js");

var dummyRepos = /* array */[RepoData$ReactTemplate.parseRepoJson(JSON.parse("\n        {\n          \"stargazers_count\": 93,\n          \"full_name\": \"reasonml/reason-tools\",\n          \"html_url\": \"https://github.com/reasonml/reason-tools\"\n        }\n      "))];

function App(Props) {
  var match = React.useState((function () {
          return undefined;
        }));
  var setRepoData = match[1];
  var repoData = match[0];
  React.createElement("button", {
        onClick: (function (_event) {
            return Curry._1(setRepoData, (function (_prev) {
                          return dummyRepos;
                        }));
          })
      }, "Load Repos");
  React.useEffect((function () {
          RepoData$ReactTemplate.fetchRepos(/* () */0).then((function (repoData) {
                    Curry._1(setRepoData, (function (_prev) {
                            return repoData;
                          }));
                    return Promise.resolve(/* () */0);
                  })).catch((function (err) {
                  console.log("An error occurred: " + String(err));
                  return Promise.resolve(/* () */0);
                }));
          return undefined;
        }), ([]));
  var repoItems = repoData !== undefined ? $$Array.map((function (repo) {
            return React.createElement(RepoItem$ReactTemplate.make, {
                        repo: repo,
                        key: repo[/* full_name */0]
                      });
          }), repoData) : "Loading...";
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Reason Projects"), repoItems);
}

var dummyRepo = /* record */[
  /* full_name */"jsdf/reason-react-hacker-news",
  /* stargazers_count */27,
  /* html_url */"https://github.com/jsdf/reason-react-hacker-news"
];

var make = App;

exports.dummyRepo = dummyRepo;
exports.dummyRepos = dummyRepos;
exports.make = make;
/* dummyRepos Not a pure module */
